# Generated by Django 6.0.8 on 2026-08-19 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_alter_ngo_administrator_organizationmembership"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerifiedNGORegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("registration_number", models.CharField(max_length=100, unique=True)),
                ("address", models.TextField(blank=True)),
                (
                    "source_name",
                    models.CharField(
                        default="Bangladesh NGO Affairs Bureau", max_length=150
                    ),
                ),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="ngo",
            name="registration_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="ngo",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("VERIFIED", "Verified"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ngo",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ngo",
            name="registry_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="platform_ngos",
                to="organizations.verifiedngoregistry",
            ),
        ),
    ]
