# Generated by Django 6.0.8 on 2026-08-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_verifiedngoregistry_ngo_registration_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="verifiedngoregistry",
            name="country",
            field=models.CharField(default="Bangladesh", max_length=100),
        ),
        migrations.AddField(
            model_name="verifiedngoregistry",
            name="district",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="verifiedngoregistry",
            name="registration_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="verifiedngoregistry",
            name="remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="verifiedngoregistry",
            name="renewed_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="verifiedngoregistry",
            name="valid_upto",
            field=models.DateField(blank=True, null=True),
        ),
    ]
