# Generated by Django 6.0.8 on 2026-08-15 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_event_coordinator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('REGISTRATION_RECEIVED', 'Registration Received'), ('REGISTRATION_APPROVED', 'Registration Approved'), ('REGISTRATION_REJECTED', 'Registration Rejected'), ('EVENT_PUBLISHED', 'New Event Published'), ('EVENT_REMINDER', 'Event Reminder'), ('TEAM_ASSIGNED', 'Team Assigned'), ('DONATION_RECEIVED', 'Donation Received')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='events.event')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='events.registration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
