# Generated by Django 6.0.8 on 2026-08-24 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
        ('notifications', '0002_notification_donation_notification_team_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='certificates.certificate'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('REGISTRATION_RECEIVED', 'Registration Received'), ('REGISTRATION_APPROVED', 'Registration Approved'), ('REGISTRATION_REJECTED', 'Registration Rejected'), ('EVENT_PUBLISHED', 'New Event Published'), ('EVENT_REMINDER', 'Event Reminder'), ('TEAM_ASSIGNED', 'Team Assigned'), ('DONATION_RECEIVED', 'Donation Received'), ('COORDINATOR_ASSIGNED', 'Coordinator Assigned'), ('CERTIFICATE_ISSUED', 'Certificate Issued')], max_length=30),
        ),
    ]
