# Generated by Django 6.0.8 on 2026-08-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('REGISTRATION_RECEIVED', 'Registration Received'), ('REGISTRATION_APPROVED', 'Registration Approved'), ('REGISTRATION_REJECTED', 'Registration Rejected'), ('EVENT_PUBLISHED', 'New Event Published'), ('EVENT_REMINDER', 'Event Reminder'), ('TEAM_ASSIGNED', 'Team Assigned'), ('DONATION_RECEIVED', 'Donation Received'), ('DONATION_SENT', 'Donation Sent'), ('DONATION_ACKNOWLEDGED', 'Donation Acknowledged'), ('COORDINATOR_ASSIGNED', 'Coordinator Assigned'), ('COORDINATOR_REMOVED', 'Coordinator Removed'), ('CERTIFICATE_ISSUED', 'Certificate Issued')], max_length=30),
        ),
    ]
